<?php

if (function_exists('acf_add_options_page')) {

    acf_add_options_page(array(
        'page_title'     => __('Opções do tema', 'naturgy'),
        'menu_title'    => __('Opções do tema', 'naturgy'),
        'menu_slug'     => 'theme-settings',
        'capability'    => 'edit_posts',
        'redirect'        => false
    ));

    acf_add_options_sub_page(array(
        'page_title'    => 'PopUp Configurações',
        'menu_title'    => 'PopUp',
        'parent_slug'   => 'theme-settings',
        'post_id' => 'PopUp-settings',
    ));
}

add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_64146b7d9e312',
        'title' => 'PopUp',
        'fields' => array(
            array(
                'show_column_filter' => 0,
                'allow_bulkedit' => 0,
                'allow_quickedit' => 0,
                'show_column' => 0,
                'show_column_weight' => 1000,
                'show_column_sortable' => false,
                'key' => 'field_64146fbbe1f9e',
                'label' => 'Exibir PopUp?',
                'name' => 'exibir_popup',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Sempre' => 'Sempre',
                    '1x Dia' => '1x Dia',
                    'ocultar' => 'Ocultar',
                ),
                'default_value' => '',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ),
            array(
                'show_column_filter' => false,
                'allow_bulkedit' => false,
                'allow_quickedit' => false,
                'show_column' => false,
                'show_column_weight' => 1000,
                'show_column_sortable' => false,
                'key' => 'field_641483adbac5b',
                'label' => 'Atenção!',
                'name' => '',
                'aria-label' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Os PopUps seguirão a prioridade da ordem definida abaixo, depois a ordem da data de inicio da exibição.',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'show_column_filter' => false,
                'allow_bulkedit' => false,
                'allow_quickedit' => false,
                'show_column' => false,
                'show_column_weight' => 1000,
                'show_column_sortable' => false,
                'key' => 'field_64146b7f0a4ff',
                'label' => 'PopUp',
                'name' => 'popup',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 1,
                'collapsed' => '',
                'button_label' => 'Adicionar Linha',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'show_column_filter' => false,
                        'allow_bulkedit' => false,
                        'allow_quickedit' => false,
                        'show_column' => false,
                        'show_column_weight' => 1000,
                        'show_column_sortable' => false,
                        'key' => 'field_641cb3fbe7fb4',
                        'label' => 'Informações',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'parent_repeater' => 'field_64146b7f0a4ff',
                    ),
                    array(
                        'show_column_filter' => false,
                        'allow_bulkedit' => false,
                        'allow_quickedit' => false,
                        'show_column' => false,
                        'show_column_weight' => 1000,
                        'show_column_sortable' => false,
                        'key' => 'field_641cb3b536c11',
                        'label' => 'Infos',
                        'name' => 'infos',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'parent_repeater' => 'field_64146b7f0a4ff',
                        'sub_fields' => array(
                            array(
                                'show_column_filter' => 0,
                                'allow_bulkedit' => 0,
                                'allow_quickedit' => 0,
                                'show_column' => 0,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_649f54a840017',
                                'label' => 'Tipo do PopUp',
                                'name' => 'tipo_do_popup',
                                'aria-label' => '',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'imagem' => 'Imagem',
                                    'criacao' => 'Criação',
                                ),
                                'default_value' => '',
                                'return_format' => 'value',
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'layout' => 'vertical',
                                'save_other_choice' => 0,
                            ),
                            array(
                                'show_column_filter' => false,
                                'allow_bulkedit' => false,
                                'allow_quickedit' => false,
                                'show_column' => false,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_649f541deed20',
                                'label' => 'Criação',
                                'name' => 'criacao',
                                'aria-label' => '',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_649f54a840017',
                                            'operator' => '==',
                                            'value' => 'criacao',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => 0,
                                        'allow_quickedit' => 0,
                                        'show_column' => 0,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_641cb09f14500',
                                        'label' => 'Sobre Título',
                                        'name' => 'sobre_titulo',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => false,
                                        'allow_quickedit' => false,
                                        'show_column' => false,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_641cb0a914501',
                                        'label' => 'Título',
                                        'name' => 'titulo',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'rows' => 2,
                                        'placeholder' => '',
                                        'new_lines' => '',
                                    ),
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => false,
                                        'allow_quickedit' => false,
                                        'show_column' => false,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_641cb0c614502',
                                        'label' => 'Texto',
                                        'name' => 'texto',
                                        'aria-label' => '',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => false,
                                        'allow_quickedit' => false,
                                        'show_column' => false,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_64146b990a501',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                    ),
                                ),
                            ),
                            array(
                                'show_column_filter' => false,
                                'allow_bulkedit' => false,
                                'allow_quickedit' => false,
                                'show_column' => false,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_649f542deed21',
                                'label' => 'Imagem',
                                'name' => 'imagem',
                                'aria-label' => '',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_649f54a840017',
                                            'operator' => '==',
                                            'value' => 'imagem',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => false,
                                        'allow_quickedit' => false,
                                        'show_column' => false,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_649f545deed22',
                                        'label' => 'Imagem',
                                        'name' => 'imagem',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'medium',
                                    ),
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => false,
                                        'allow_quickedit' => false,
                                        'show_column' => false,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_649f55c845c8c',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'show_column_filter' => false,
                        'allow_bulkedit' => false,
                        'allow_quickedit' => false,
                        'show_column' => false,
                        'show_column_weight' => 1000,
                        'show_column_sortable' => false,
                        'key' => 'field_641cb406e7fb5',
                        'label' => 'Datas',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'parent_repeater' => 'field_64146b7f0a4ff',
                    ),
                    array(
                        'show_column_filter' => false,
                        'allow_bulkedit' => false,
                        'allow_quickedit' => false,
                        'show_column' => false,
                        'show_column_weight' => 1000,
                        'show_column_sortable' => false,
                        'key' => 'field_64146bb90a502',
                        'label' => 'Data',
                        'name' => 'data',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'parent_repeater' => 'field_64146b7f0a4ff',
                        'sub_fields' => array(
                            array(
                                'show_column_filter' => false,
                                'allow_bulkedit' => 0,
                                'allow_quickedit' => 0,
                                'show_column' => 0,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_64146bd50a503',
                                'label' => 'Início',
                                'name' => 'inicio',
                                'aria-label' => '',
                                'type' => 'date_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'd/m/Y',
                                'return_format' => 'd/m/Y',
                                'first_day' => 1,
                            ),
                            array(
                                'show_column_filter' => false,
                                'allow_bulkedit' => 0,
                                'allow_quickedit' => 0,
                                'show_column' => 0,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_64146be60a504',
                                'label' => 'Final',
                                'name' => 'final',
                                'aria-label' => '',
                                'type' => 'date_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'd/m/Y',
                                'return_format' => 'd/m/Y',
                                'first_day' => 1,
                            ),
                        ),
                    ),
                    array(
                        'show_column_filter' => false,
                        'allow_bulkedit' => false,
                        'allow_quickedit' => false,
                        'show_column' => false,
                        'show_column_weight' => 1000,
                        'show_column_sortable' => false,
                        'key' => 'field_642309b38df01',
                        'label' => 'Configs',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                        'parent_repeater' => 'field_64146b7f0a4ff',
                    ),
                    array(
                        'show_column_filter' => false,
                        'allow_bulkedit' => false,
                        'allow_quickedit' => false,
                        'show_column' => false,
                        'show_column_weight' => 1000,
                        'show_column_sortable' => false,
                        'key' => 'field_642309bd8df02',
                        'label' => 'Configurações',
                        'name' => 'configuracoes',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'parent_repeater' => 'field_64146b7f0a4ff',
                        'sub_fields' => array(
                            array(
                                'show_column_filter' => 0,
                                'allow_bulkedit' => 0,
                                'allow_quickedit' => 0,
                                'show_column' => 0,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_64230af38df05',
                                'label' => 'Exibição',
                                'name' => 'exibicao',
                                'aria-label' => '',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui_on_text' => 'Apenas em:',
                                'ui_off_text' => 'Em todas',
                                'ui' => 1,
                            ),
                            array(
                                'show_column_filter' => false,
                                'allow_bulkedit' => false,
                                'allow_quickedit' => false,
                                'show_column' => false,
                                'show_column_weight' => 1000,
                                'show_column_sortable' => false,
                                'key' => 'field_642309e38df03',
                                'label' => 'Links',
                                'name' => 'links',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_64230af38df05',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'pagination' => 0,
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Adicionar Linha',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'show_column_filter' => false,
                                        'allow_bulkedit' => false,
                                        'allow_quickedit' => false,
                                        'show_column' => false,
                                        'show_column_weight' => 1000,
                                        'show_column_sortable' => false,
                                        'key' => 'field_64230aea8df04',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'parent_repeater' => 'field_642309e38df03',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-popup',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
